// Import CSS files
import 'swiper/swiper-bundle.css'
import '../css/common.scss'
import '../css/header.scss'
import '../css/style.scss'
import '../css/about.scss'
import '../css/advantages.scss'
import '../css/contacts.scss'
import '../css/cooperation.scss'
import '../css/fulfillment.scss'
import '../css/calculator.scss'
import '../css/our-clients.scss'
import '../css/reviews.scss'
import '../css/modal.scss'
import '../css/footer.scss'

// Import JS files
import './modal'
import './slider'
import './mobile-slider'
import './upload-button'
import './main-nav-mobile'
